package com.pan.apiprodutos.messaging

const val QUEUE_PROCESSA_ENTREGA = "QUEUE_PROCESSA_ENTREGA"
const val QUEUE_ENTREGA_PROCESSADA = "QUEUE_ENTREGA_PROCESSADA"
const val EXCHANGE_ENTREGA = "EXCHANGE_ENTREGA"