package com.pan.apientregas.constant

const val QUEUE_PROCESSA_ENTREGA = "QUEUE_PROCESSA_ENTREGA"
const val QUEUE_ENTREGA_PROCESSADA = "QUEUE_ENTREGA_PROCESSADA"
const val EXCHANGE_ENTREGA = "EXCHANGE_ENTREGA"
const val KEY_PROCESSA = "KEY_PROCESSA"
const val KEY_PROCESSADA = "KEY_PROCESSADA"